USE [MASTER]
GO

CREATE LOGIN [MyDomain\MyADGroup] FROM WINDOWS WITH DEFAULT_DATABASE = [MASTER]
GO

USE [MyDB]
GO

CREATE USER [MyDomain\MyADGroup] FOR LOGIN [MyDomain\MyADGroup]
GO

GRANT EXECUTE ON SCHEMA:: MYSCHEMA TO [MyDomain\MyADGroup]
GO

GRANT SELECT ON SCHEMA:: MYSCHEMA TO [MyDomain\MyADGroup]
GO

GRANT VIEW DEFINITION ON SCHEMA:: MYSCHEMA TO [MyDomain\MyADGroup]
GO